server {
    listen 80;
    server_name auth.home;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name auth.home;
    include /etc/nginx/snippets/ssl.conf;

    location / {
        proxy_pass http://rocket-auth:8000;
        proxy_set_header Host $host;
        proxy_set_header Cookie $http_cookie;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
